# Generated by Django 6.1.1 on 2026-09-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialestado',
            name='es_correccion',
            field=models.BooleanField(default=False, help_text='True si el registro corresponde a una solicitud de corrección (el estado no cambia, solo se registra la observación).'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='observacion_correccion',
            field=models.TextField(blank=True, help_text='Descripción de lo que el estudiante debe corregir en la etapa actual.'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='requiere_correccion',
            field=models.BooleanField(default=False, help_text='True si el estudiante tiene una observación pendiente en la etapa actual.'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_auxiliar',
            field=models.BooleanField(default=False, help_text='Solo aplica si rol == ADMIN. Con este flag activo el usuario puede consultar procesos y gestionar notificaciones, pero NO puede aprobar etapas ni administrar usuarios.'),
        ),
    ]
