# Generated by Django 6.1.1 on 2026-09-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historialestado_es_correccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Descripción o notas del documento adjunto.'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='mensaje_asesor',
            field=models.TextField(blank=True, default='', help_text='Instrucciones o directriz del Admin/Comité para el Asesor asignado.'),
        ),
    ]
