# Generated by Django 6.1.1 on 2026-09-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_documento_descripcion_postulacion_mensaje_asesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='archivo_correccion',
            field=models.FileField(blank=True, help_text='Archivo de retroalimentación o documento comentado por el evaluador/asesor.', null=True, upload_to='correcciones/%Y/%m/'),
        ),
    ]
