# Generated by Django 6.1.1 on 2026-09-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_postulacion_archivo_correccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='mensaje_subsanacion',
            field=models.TextField(blank=True, default='', help_text='Explicación del estudiante al subsanar las observaciones de corrección.'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='subsanado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la última subsanación enviada por el estudiante.', null=True),
        ),
    ]
