# Generated by Django 6.1.1 on 2026-09-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_postulacion_mensaje_subsanacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='archivo_sustentacion',
            field=models.FileField(blank=True, help_text='Documento opcional adjunto por el asesor sobre la sustentación.', null=True, upload_to='sustentaciones/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='mensaje_sustentacion',
            field=models.TextField(blank=True, default='', help_text='Mensaje del asesor al estudiante con detalles de la sustentación (fecha, hora, etc.).'),
        ),
    ]
