# Generated by Django 6.1.1 on 2026-09-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_postulacion_sustentacion_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='archivo_asesor',
            field=models.FileField(blank=True, help_text='Documento opcional adjunto por Admin/Comité al asignar/enviar al asesor.', null=True, upload_to='mensajes_asesor/%Y/%m/'),
        ),
    ]
