# Generated by Django 6.1.1 on 2026-09-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_postulacion_archivo_asesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialestado',
            name='estado_anterior',
            field=models.CharField(choices=[('POSTULACION', 'Postulación'), ('REVISION_DOCUMENTAL', 'Revisión Documental'), ('APROBACION', 'Aprobación'), ('EN_PROCESO', 'En Proceso'), ('SUSTENTACION', 'Sustentación'), ('REVISION_COMITE', 'Revisión Comité'), ('FINALIZADO', 'Finalizado'), ('RECHAZADO', 'Rechazado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_nuevo',
            field=models.CharField(choices=[('POSTULACION', 'Postulación'), ('REVISION_DOCUMENTAL', 'Revisión Documental'), ('APROBACION', 'Aprobación'), ('EN_PROCESO', 'En Proceso'), ('SUSTENTACION', 'Sustentación'), ('REVISION_COMITE', 'Revisión Comité'), ('FINALIZADO', 'Finalizado'), ('RECHAZADO', 'Rechazado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='estado',
            field=models.CharField(choices=[('POSTULACION', 'Postulación'), ('REVISION_DOCUMENTAL', 'Revisión Documental'), ('APROBACION', 'Aprobación'), ('EN_PROCESO', 'En Proceso'), ('SUSTENTACION', 'Sustentación'), ('REVISION_COMITE', 'Revisión Comité'), ('FINALIZADO', 'Finalizado'), ('RECHAZADO', 'Rechazado')], default='POSTULACION', max_length=30),
        ),
    ]
